// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVaxoglp3jiAYiG8b25B0yCg9L3pbZ0co',
    appId: '1:400489777398:web:21c8924527259eec43c4d7',
    messagingSenderId: '400489777398',
    projectId: 'test-1-a7021',
    authDomain: 'test-1-a7021.firebaseapp.com',
    storageBucket: 'test-1-a7021.appspot.com',
    measurementId: 'G-TG4H0DEMBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbSp0ACeSnoxQ_Kk73tZHzHpkLL_nryc4',
    appId: '1:400489777398:android:07ca45f53868455643c4d7',
    messagingSenderId: '400489777398',
    projectId: 'test-1-a7021',
    storageBucket: 'test-1-a7021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz3fHEi_tSfxzKYyclxn_UjbmuJ-5tdT4',
    appId: '1:400489777398:ios:8ca1392ed50112cf43c4d7',
    messagingSenderId: '400489777398',
    projectId: 'test-1-a7021',
    storageBucket: 'test-1-a7021.appspot.com',
    iosClientId: '400489777398-2h1nps6erd869ln2ot0307dm6g80m8ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.kods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz3fHEi_tSfxzKYyclxn_UjbmuJ-5tdT4',
    appId: '1:400489777398:ios:c5a63e3f6069b7bd43c4d7',
    messagingSenderId: '400489777398',
    projectId: 'test-1-a7021',
    storageBucket: 'test-1-a7021.appspot.com',
    iosClientId: '400489777398-l0nq81h6smht2pgd3ldq9uvjaesuqbg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.kods.RunnerTests',
  );
}
